splash = false
wallpaper {
    monitor = DP-1
    path = $HOME/.config/hypr/Wallpapers/anime/rei-asuka.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = $HOME/.config/hypr/Wallpapers/anime/rei-asuka.jpg
    fit_mode = cover
}
